### ISSUE TITLE
Improve layout for ports

### ISSUE THREAD

**Issue by etolbakov** [etolbakov/excalidocker-rs#29]
When a docker image exposes several ports the layout has issues.
```
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9044:9044"
      - "9055:9055"
```
It affects all 3 alignment modes (`vertical`, `horizontal`, `stepped`. Might need to consider a totally different way of drawing ports
<img width="604" alt="image003" src="https://github.com/etolbakov/excalidocker-rs/assets/3762201/27564ede-3c39-4adf-971e-6f69ed3540cb">
<img width="586" alt="image002" src="https://github.com/etolbakov/excalidocker-rs/assets/3762201/58051554-a130-4aba-a7ad-9d41032b7ecc">
<img width="500" alt="image001" src="https://github.com/etolbakov/excalidocker-rs/assets/3762201/dffd6998-f66b-4067-9268-9e2f1dbd2f2e">

 
https://github.com/etolbakov/excalidocker-rs/issues/20
