### ISSUE TITLE
Config to support word colour format

### ISSUE THREAD

**Issue by etolbakov** [etolbakov/excalidocker-rs#37]
Currently [excalidocker-config.yaml](https://github.com/etolbakov/excalidocker-rs/blob/8dc406a943eae89e6a1ee19d9e1392445ab59575/excalidocker-config.yaml#L1) supports only `hex` format for colors
```yaml
...
services: # rectangle
  background_color: "#b2f2bb"
....
ports: # ellipse
  background_color: "#a5d8ff"
....
```
It would be helpful to let users specify colors like `red`, `blue`, `green`, etc.
Potentially - this crate can be useful
https://docs.rs/hex_color/latest/hex_color/
